# Model level explanations {#ModelLevelExplanations}

# Introduction

Model level explainers help to understand how the model works in general, for some population of interest. This is the main difference from the instance level explainers that were focused on a model behaviour around a single observation. Model level explainers work in the context of a population or subpopulation.

Think about following use-cases

* One wants to know which variables are important in the model. Think about model for heart accident in which features come from additional medical examinations. Knowing which examinations are not important one can reduce a model by removing unnecessary variables.
* One wants to understand how a selected variable affects the model response. Think about a model for prediction of apartment prices. You know that apartment location is an important factor, but which locations are better and how much a given location is worth? Model explainers help to understand how values of a selected variable affect the model response.
* One wants to know if there are any unusual observations that do not fit to the model. Observations with unusually large residuals. Think about a model for survival after some very risky treatment. You would like to know if for some patients the model predictions are extremely incorrect.

All cases mentioned above are linked with either model diagnostic (checking if model behaves alog our expectations) or knowledge extraction (model was trained to extract some knowledge about the discipline).

## Approaches to model explanations

Model level explanations are focused on four main aspects of a model. 

* Model performance. Here the question is how good is the model, is it good enough (better than some predefined threshold), is a model A better than model B?
* Variable importance. How important are variables, which are the most important and which are not important at all?
* Variable effects. What is the relation between a variable and model response, can the variable be transformed to create a better model?
* Model residuals. Is there any unusual pattern related to residuals, are they biased, are they correlated with some additional variable?



## A bit of philosophy: Three Laws for Model Level Explanations

In the spirit of three laws introduces in the chapter \@ref(three-single-laws) here we propose three laws for model level explanations.

* **Variable importance.** For every model we shall be able to understand which variables are important and which are not.
* **Model audit.** For every model we shall be able to verify basic check like if residuals are correlated with variables and if there are unusual observations.
* **Second opinion.**  For every model we shall be able to compare it against other models to verify if they capture different stories about the data.



